# Application Configuration
spring.application.name=RevWorkForce
server.port=8081

# Oracle Database Configuration
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
<<<<<<< HEAD
spring.datasource.username= workforce_db
=======
spring.datasource.username= "revworkforce-db"
>>>>>>> main
spring.datasource.password= revpassword
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
<<<<<<< HEAD
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
=======
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


>>>>>>> main
